"""Write ``tests/fixtures/team_code_vectors.json``: shared team-code test vectors.

pytest (``tests/test_team_code.py``) and the P7 TypeScript implementation both check these, so
Python and TypeScript agree byte for byte. Re-run only when the code format changes (and bump
``team_code.VERSION``):

    python scripts/make_team_code_vectors.py
"""

from __future__ import annotations

import json
import struct

from fPLense import config, team_code

OUT = config.TESTS_FIXTURES_DIR / "team_code_vectors.json"

# Synthetic player table (ids/positions/clubs), not real FPL players: the vectors test the
# format, and validate() runs against this table.
PLAYERS = {
    **{i: {"pos": "GK", "club": f"C{i}", "price": 45} for i in (1, 2)},
    **{i: {"pos": "DEF", "club": f"C{i}", "price": 50} for i in (10, 11, 12, 13, 14)},
    **{i: {"pos": "MID", "club": f"C{i}", "price": 70} for i in (20, 21, 22, 23, 24)},
    **{i: {"pos": "FWD", "club": f"C{i}", "price": 80} for i in (30, 31, 32)},
    600: {"pos": "MID", "club": "C0", "price": 150},
    601: {"pos": "FWD", "club": "C0", "price": 145},
    65535: {"pos": "DEF", "club": "C5", "price": 40},
}

VALID = [
    {
        "name": "3-4-3, bench GK last",
        "starters": [1, 10, 11, 12, 20, 21, 22, 23, 30, 31, 32],
        "bench": [24, 13, 14, 2],
        "captain": 30,
        "vice": 20,
    },
    {
        "name": "5-4-1, captain is the last starter",
        "starters": [2, 10, 11, 12, 13, 14, 20, 21, 22, 23, 30],
        "bench": [31, 24, 32, 1],
        "captain": 30,
        "vice": 2,
    },
    {
        "name": "large ids (600, 601, 65535)",
        "starters": [1, 10, 11, 65535, 600, 21, 22, 23, 601, 31, 32],
        "bench": [12, 24, 13, 2],
        "captain": 600,
        "vice": 601,
    },
]


def raw_code(version: int, season: int, ids: list[int], armbands: int, prefix_season: int) -> str:
    body = struct.pack(">BH15HB", version, season, *ids, armbands)
    data = body + bytes([team_code.crc8(body)])
    return f"FPLN-{prefix_season:04d}-{team_code.b32encode(data)}"


def main() -> None:
    season = team_code.season_number()
    valid = []
    for v in VALID:
        code = team_code.encode(v["starters"], v["bench"], v["captain"], v["vice"])
        team = team_code.TeamCode(
            season, tuple(v["starters"] + v["bench"]), v["captain"], v["vice"]
        )
        valid.append(
            {**v, "season": season, "bytes_hex": team_code.payload(team).hex(), "code": code}
        )
    base = VALID[0]["starters"] + VALID[0]["bench"]
    invalid = [
        {"name": "junk", "input": "hello world", "kind": "junk"},
        {"name": "truncated", "input": valid[0]["code"][:-3], "kind": "typo"},
        {
            "name": "bad checksum (last char changed)",
            "input": valid[0]["code"][:-1] + ("0" if valid[0]["code"][-1] != "0" else "1"),
            "kind": "typo",
        },
        {
            "name": "code from 2025-26",
            "input": raw_code(1, 2526, base, (8 << 4) | 4, 2526),
            "kind": "season",
        },
        {
            "name": "format version 2",
            "input": raw_code(2, season, base, (8 << 4) | 4, season),
            "kind": "version",
        },
        {
            "name": "duplicate player",
            "input": raw_code(1, season, [1, *base[:-1]], 0x84, season),
            "kind": "duplicate",
        },
        {
            "name": "captain index out of range",
            "input": raw_code(1, season, base, (11 << 4) | 4, season),
            "kind": "captain",
        },
        {
            "name": "prefix season edited",
            "input": valid[0]["code"].replace(f"-{season}-", "-2526-"),
            "kind": "typo",
        },
    ]
    doc = {
        "about": "FPLense team-code vectors (PLAN.md §8 P6); generated by "
        "scripts/make_team_code_vectors.py. Players are synthetic.",
        "format": "version u8 | season u16 | 15 x id u16 | captain_idx<<4 | vice_idx | CRC-8 "
        "(poly 0x07, init 0), big-endian, Crockford base32, prefix FPLN-<season>-",
        "crc8_check": {"input_ascii": "123456789", "crc": team_code.crc8(b"123456789")},
        "season": season,
        "players": {str(k): v for k, v in PLAYERS.items()},
        "valid": valid,
        "invalid": invalid,
    }
    OUT.write_text(json.dumps(doc, indent=1), encoding="utf-8")
    print(f"-> {OUT} ({len(valid)} valid, {len(invalid)} invalid)")


if __name__ == "__main__":
    main()
